'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import type { BranchCode,StoryProposal } from '@/types/story';
type RuntimeState={episodeNumber:number;status:string;previousSummary?:string;mode?:string};

export default function Today(){
  const router=useRouter(); const [proposal,setProposal]=useState<StoryProposal|null>(null); const [selected,setSelected]=useState<BranchCode|''>(''); const [loading,setLoading]=useState(true); const [generating,setGenerating]=useState(false); const [mode,setMode]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{(async()=>{try{const s=await fetch('/api/state',{cache:'no-store'}).then(r=>r.json()); const state:RuntimeState=s.data||{episodeNumber:1,status:'WAITING_DECISION'}; const key=`storyProposal:${state.episodeNumber}`; const cached=localStorage.getItem(key); if(cached){try{setProposal(JSON.parse(cached));setMode(state.mode||'');setLoading(false);return;}catch{}} const r=await fetch('/api/story/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({episodeNumber:state.episodeNumber,previousSummary:state.previousSummary})}); if(!r.ok)throw new Error('候補生成に失敗しました'); const j=await r.json(); setProposal(j.data);setMode(j.mode||'');localStorage.setItem(key,JSON.stringify(j.data));}catch(e){setError(e instanceof Error?e.message:'読み込みに失敗しました');}finally{setLoading(false);}})();},[]);
  async function adopt(){if(!selected||!proposal)return;setGenerating(true);setError('');try{localStorage.setItem('selectedBranch',selected);const branch=proposal.branches.find(b=>b.code===selected); if(!branch)return; localStorage.setItem('selectedConcept',JSON.stringify(branch)); const save=await fetch('/api/episode/select',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({episodeNumber:proposal.episodeNumber,code:selected})}); if(!save.ok)throw new Error('選択を保存できませんでした'); const r=await fetch('/api/content/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({episodeNumber:proposal.episodeNumber,previousSummary:proposal.previousSummary,choiceChainSummary:proposal.choiceChainSummary,selectedBranch:branch})}); if(!r.ok)throw new Error('投稿生成に失敗しました'); const j=await r.json();localStorage.setItem('generatedContent',JSON.stringify(j.data));localStorage.setItem('contentMode',j.mode||'');try{const mr=await fetch('/api/media/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imagePrompt:j.data.imagePrompt,videoPrompt:j.data.videoPrompt})});localStorage.setItem('mediaState',JSON.stringify(await mr.json()));}catch{localStorage.removeItem('mediaState');}router.push('/review');}catch(e){setError(e instanceof Error?e.message:'処理に失敗しました');}finally{setGenerating(false);}}
  return <>
    <div className="top"><div className="brand">AI STORY</div><span className="pill">{proposal?`EP ${String(proposal.episodeNumber).padStart(3,'0')}`:'TODAY'}</span></div>
    <section className="card result-card"><div className="eyebrow">YESTERDAY → TODAY</div><h1 className="title">昨日の選択を今日に反映</h1><p className="sub">{proposal?.previousSummary||'前日の結果を読み込んでいます。'}</p>{proposal?.choiceChainSummary&&<div className="chain">{proposal.choiceChainSummary}</div>}</section>
    <section className="card"><div className="eyebrow">TODAY</div><h2 className="title">今日の投稿を1つ選ぶ</h2><p className="sub">あなたは3案から選ぶだけ。視聴者にはシンプルな二択として投稿されます。</p>
      {loading&&<p className="sub">候補を準備しています…</p>}{error&&<p className="notice">{error}</p>}
      {proposal&&<><div className="grid3">{proposal.branches.map(b=><button key={b.code} className={'choice '+(selected===b.code?'active':'')} onClick={()=>setSelected(b.code)}><span className="choice-code">{b.code}</span><b>{b.title}</b><p className="sub">{b.description}</p><div className="audience-choice"><span>{b.audienceChoiceA}</span><i>or</i><span>{b.audienceChoiceB}</span></div><p className="score">AI {b.aiScore} ・ 継続 {b.continuity}</p></button>)}</div><div className="recommend"><b>AIおすすめ：{proposal.recommendation}</b><span>{proposal.recommendationReason}</span></div>{mode==='fallback'&&<p className="hint">現在はデモ生成。OPENAI_API_KEY設定後は実AIで日常二択を生成します。</p>}<button className="cta" disabled={!selected||generating} onClick={adopt}>{generating?'投稿を作成中…':selected?`${selected}を採用して投稿を作る`:'1つ選んでください'}</button></>}
    </section>
    <section className="card funnel-card"><div className="eyebrow">FUNNEL</div><div className="funnel"><span>VIEW</span><b>→</b><span>VOTE</span><b>→</b><span>RETURN</span><b>→</b><span>PROFILE</span><b>→</b><span>LINK</span><b>→</b><span>PAID</span></div><p className="sub">v0.5ではまず VIEW → VOTE → RETURN を検証。課金はまだ開放しません。</p></section>
  </>;
}
