'use client';
import { useEffect,useState } from 'react';
import type { GeneratedContent } from '@/types/story';
type MediaState={enabled?:boolean;imageDataUrl?:string|null;imageWarning?:string|null;video?:{id:string;status:string;progress?:number}|null;videoWarning?:string|null};
export default function Review(){
 const [content,setContent]=useState<GeneratedContent|null>(null);const [media,setMedia]=useState<MediaState|null>(null);const [publishing,setPublishing]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{const s=localStorage.getItem('generatedContent'),m=localStorage.getItem('mediaState');if(s)try{setContent(JSON.parse(s));}catch{}if(m)try{setMedia(JSON.parse(m));}catch{}},[]);
 useEffect(()=>{const id=media?.video?.id,status=media?.video?.status;if(!id||!['queued','in_progress'].includes(status||''))return;const t=setInterval(async()=>{try{const j=await fetch(`/api/media/video/status?id=${encodeURIComponent(id)}`,{cache:'no-store'}).then(r=>r.json());if(j.ok)setMedia((p: MediaState | null)=>{const n={...(p||{}),video:j.video};localStorage.setItem('mediaState',JSON.stringify(n));return n;});}catch{}},12000);return()=>clearInterval(t);},[media?.video?.id,media?.video?.status]);
 async function regenerate(){if(!content)return;setMessage('再生成しています…');const concept=localStorage.getItem('selectedConcept');const r=await fetch('/api/content/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({episodeNumber:content.episodeNumber,selectedBranch:concept?JSON.parse(concept):undefined,regenerate:true})});const j=await r.json();setContent(j.data);localStorage.setItem('generatedContent',JSON.stringify(j.data));try{const mr=await fetch('/api/media/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imagePrompt:j.data.imagePrompt,videoPrompt:j.data.videoPrompt})});const mj=await mr.json();setMedia(mj);localStorage.setItem('mediaState',JSON.stringify(mj));}catch{}setMessage('作り直しました。');}
 async function publish(){setPublishing(true);const j=await fetch('/api/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({episodeNumber:content?.episodeNumber,videoId:media?.video?.id})}).then(r=>r.json());setMessage(j.message||'承認しました。');localStorage.setItem('publishState',JSON.stringify(j));setPublishing(false);}
 if(!content)return <><div className="top"><div className="brand">投稿確認</div></div><section className="card"><h1 className="title">まだ投稿がありません</h1><p className="sub">「今日」から日常テーマを選んでください。</p></section></>;
 const ready=media?.video?.status==='completed';return <><div className="top"><div className="brand">投稿確認</div><span className="status">READY</span></div><section className="card"><div className="eyebrow">EPISODE {String(content.episodeNumber).padStart(3,'0')}</div><div className="payoff"><b>昨日 → 今日</b><span>{content.continuityNote}</span></div>{ready&&media?.video?.id?<video className="video" controls playsInline src={`/api/media/video/content?id=${encodeURIComponent(media.video.id)}`}/>:media?.imageDataUrl?<img className="video" src={media.imageDataUrl} alt="生成プレビュー" style={{objectFit:'cover'}}/>:<div className="video"><div><b>DAILY LIFE PREVIEW</b><br/><small>{media?.enabled===false?'メディア生成OFF':media?.video?.status?`動画 ${media.video.status} ${media.video.progress??0}%`:'画像/動画生成待ち'}</small></div></div>}{media?.video&&!ready&&<p className="hint">動画：{media.video.status} {media.video.progress??0}%（自動更新）</p>}<h2>{content.hook}</h2><p className="sub">{content.script}</p><div className="viewer-choice"><div><small>A</small><b>{content.choiceA}</b></div><span>or</span><div><small>B</small><b>{content.choiceB}</b></div></div><div className="caption-box"><span>CAPTION</span><p>{content.caption}</p></div><p className="sub">無料フェーズ：参加習慣を優先。販売文は入れません。</p>{message&&<p className="notice">{message}</p>}<div className="row"><button className="secondary" onClick={regenerate}>作り直す</button><button className="cta" disabled={publishing} onClick={publish}>{publishing?'承認中…':'公開を承認'}</button></div></section></>;
}
